spring.application.name=dtfutbol

# 1. Coordenadas de la Base de Datos (MySQL 8.0 Nativo)
spring.datasource.url=jdbc:mysql://localhost:3306/dtfutbol_core?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=9550

# 2. Configuración del ORM y Transacciones (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Optimización de Conexiones
spring.jpa.open-in-view=false